### ISSUE TITLE
`fastify` should be added as a dep to `package.json`

### ISSUE THREAD

**Issue by vjpr** [fastify/fastify-express#48]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3

### Plugin version

1

### Node.js version

16

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

BigSur

### Description

This breaks with yarn 2 and pnpm projects that expect all referenced deps to be in the package.json.

```
Error: Cannot find module 'fastify/lib/symbols'
Require stack:
- /xxx/node_modules/.pnpm/fastify-express@0.3.3/node_modules/fastify-express/index.js
```

In npm and yarn, `fastify-plugin` probably hoists `fastify` so it works.

### Steps to Reproduce

- Create pnpm project.
- Add express-fastify.
- Set `hoist: false` in `.npmrc`.

### Expected Behavior

No error.

**Comment by Eomm** [comment]
In these duplicates, you can find the workaround

https://github.com/fastify/fastify-swagger/issues/220
https://github.com/fastify/fastify-static/issues/159

The [decision](https://github.com/fastify/fastify-swagger/issues/220#issuecomment-583280362), 1 year ago, was to not add the dep.
We should re-evaluate it since npm v7 has been released
